Restructure tutorials and polish intro readme
newrelic/demo-deployer pull request #33
Opened 2020-10-15 18:45 UTC by alexronquillo

Before, there was only one story, so the tutorial README was geared toward setting up that one story. Now, there are 2 stories, with more on the way. This change reorganizes the tutorials into one folder, and rewrites the intro README to be more generic. It also links to both of the stories, which makes it easier to simply add future stories to the list.

2020-10-15 22:00 UTC, Julien4218 requested changes
Hey @alexronquillo I see we have 3 documentation PRs that have a lot of files in common. It's getting tricky to review and merge.
Could you consolidate the changes into 1 PR, or let me know which one you'd like me to review first?

2020-10-16 20:00 UTC, Julien4218 commented on documentation/user_config/README.md
> -* [Git](credentials/git/README.md)
We should keep the Git documentation, it would be useful for some cases when people have a private repository. The demo-deployer can work with those repos, and when it does the git token will be quite useful.

2020-10-16 20:02 UTC, Julien4218 reviewed
@alexronquillo I've reviewed this PR and I'm ready to merge it.
The only thing, I'm not sure we should remove the user config Git documentation, since it is still a deployer capabilities and could be use when people have private repositories.

2020-10-16 20:02 UTC, alexronquillo commented on documentation/user_config/README.md
> -* [Git](credentials/git/README.md)
Ah, makes sense. Should I just revert that commit?

2020-10-16 20:12 UTC, Julien4218 commented on documentation/user_config/README.md
> -* [Git](credentials/git/README.md)
That's not the only change I think, there use to be a Git folder under that path https://github.com/newrelic/demo-deployer/tree/restructure-tutorials/documentation/user_config/credentials 
I'm not seeing it anymore.

2020-10-16 20:49 UTC, alexronquillo commented on documentation/user_config/github.md
> +More documentation and screenshots are available from [GitHub](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token).
@Julien4218 I made the references specifically to GitHub instead of Git, in general, because the instructions and this link all point directly at GitHub. Later, if we find that GitLab or other remotes work as well, we can update this to be a little more generic, with instructions for each of the most popular sites.

2020-10-16 20:50 UTC, Julien4218 approved these changes

2020-10-16 20:50 UTC, merged