Enable new relic credential field merging
newrelic/demo-deployer pull request #42
Opened 2020-10-27 22:08 UTC by aswanson-nr

2020-10-28 17:13 UTC, Julien4218 commented on src/common/text/credential_field_merger_builder.rb
> +      def with_new_relic(credentials)
I think we can do a little different in this method. Instead of having inline statements that pulls a given value and add a specific definition with hard-coded key names, we should look into re-using the hashtable output from the newrelic credential, iterate over all the keys and add a definition for each key/value pair.
This would reduce the length of the method below, and avoid all the key name duplications. Furthermore, it would rely on the newrelic credential class to define what is exportable.

2020-10-28 17:16 UTC, Julien4218 commented on src/common/text/credential_field_merger_builder.rb
> +        git_credentials = context.get_user_config_provider().get_git_credentials()
maybe drop the 's' from all the credential single instance object names.

2020-10-28 17:18 UTC, Julien4218 commented on src/common/text/credential_field_merger_builder.rb
> +        newrelic_credentials = context.get_user_config_provider().get_new_relic_credential()
We should handle the case when there is no newrelic credential, which is a legitimate supported use case of the deployer. So when we dont have newrelic, all the merge field definitions for newrelic should be skipped.

2020-10-28 17:19 UTC, Julien4218 commented on src/install/service_field_merger_builder.rb
> +    def with_new_relic(context)
I dont think the naming is correct here. I wouldn't expect any hard/defined dependency at the install/service layer with newrelic.
I think this method is more about wiring (user) credentials.

2020-10-28 17:20 UTC, Julien4218 commented on src/install/service_field_merger_builder.rb
> +      instance.with_new_relic(context)
method name, see comment above.

2020-10-28 17:21 UTC, Julien4218 requested changes
A few things to look into perhaps.
Also it would be good to have a few tests for the service/install to ensure the credential field merger is getting wired up.

2020-10-28 22:42 UTC, aswanson-nr commented on src/common/text/credential_field_merger_builder.rb
> +      def with_new_relic(credentials)
I have updated the logic here as you suggested, let me know how it looks.

2020-10-29 17:25 UTC, Julien4218 commented on src/common/text/credential_field_merger_builder.rb
> +        instance.with_git(git_credential)
Maybe we should be consistent here in the logic to trigger the with_xxx( ) for git.
if git_credential is nil we probably shouldn't call the with_git( ) method.

2020-10-29 17:27 UTC, Julien4218 commented on src/user_config/definitions/new_relic_credential.rb
> +        def to_h(no_prefix = false)
Maybe easier would have been to parameterized the prefix itself in the method and default it to "newrelic_"?

2020-10-29 17:29 UTC, Julien4218 approved these changes
@aswanson-nr pretty good. I'll start testing. I left a couple comments.

2020-10-29 17:42 UTC, aswanson-nr commented on src/user_config/definitions/new_relic_credential.rb
> +        def to_h(no_prefix = false)
Good call, I will update the logic

2020-10-29 21:01 UTC, aswanson-nr commented
> I don't know maybe it's just me, but perhaps we could group things that deal with a same concept together. For example:
> git_credential = ...
> unless git_credential.nil
> ....
> end
> 
> Then repeat for newrelic_credential.

Ha! I was grouping them by action, but that works just as well.

2020-10-29 22:24 UTC, aswanson-nr commented on src/tags/provider.rb
> +      merger = Common::Text::CredentialFieldMergerBuilder.create(@context)
I used the `CredentialFieldMergerBuilder` here because it also includes all the global merge fields. Is there a clearer way to do this?

2020-10-29 22:29 UTC, Julien4218 commented on src/tags/provider.rb
> +      merger = Common::Text::CredentialFieldMergerBuilder.create(@context)
That seems right.

2020-10-29 22:55 UTC, Julien4218 commented
All good and working great.

2020-10-29 22:55 UTC, merged