quick fix to deploy a lambda
newrelic/demo-deployer pull request #76
Opened 2021-01-28 18:22 UTC by gabeobrien

2021-01-28 18:25 UTC, nr-kkenney commented
missing a version bump i believe

2021-01-28 18:28 UTC, nr-kkenney requested changes
needs a version bump

2021-01-28 18:29 UTC, nr-kkenney commented on src/infrastructure/definitions/aws/lambda_resource.rb
> +        def is_windows?()
i assume this is needed somewhere?

2021-01-29 17:30 UTC, nr-kkenney commented on Dockerfile
> +COPY . /mnt/deployer/
were these changes needed? i think the previous command was doing all of these.

2021-01-29 17:59 UTC, aswanson-nr commented on Dockerfile
> +COPY . /mnt/deployer/
@nr-kkenney These changes are not required. However, they do speed up the docker build, especially during development. This allows docker to cache more layers because the majority of our changes will be at this layer and not when it installs dependencies.

2021-01-29 18:05 UTC, nr-kkenney approved these changes

2021-01-29 18:20 UTC, merged